[project]
name = "ipython-icat"
version = "0.4.1"
description = "IPython magic command for displaying images in kitty terminal"
readme = "README.md"
requires-python = ">=3.8"
dependencies = [
    "ipython",
    "matplotlib",
    "pillow",
]
authors = [
    { name = "Tony Kabilan Okeke", email = "tonykabilanokeke@gmail.com" } 
]
keywords = ["ipython", "magic", "image", "display", "kitty", "icat", "ipython extension", "ghostty"]

[project.urls]
Homepage = "https://github.com/Kabilan108/ipython-icat"

[tool.setuptools.packages.find]
where = ["."]
include = ["icat*"]

[project.optional-dependencies]
dev = [
    "jupyter>=1.1.1",
    "ruff",
    "ty",
]

[tool.ruff.lint]
select = [
    "E",  # pycodestyle errors
    "F",  # Pyflakes
    "W",  # pycodestyle warnings
    "C90", # mccabe complexity
    "I",  # isort
    "N",  # pep8-naming
    "UP", # pyupgrade
    "B",  # flake8-bugbear
    "A",  # flake8-builtins
    "SIM",# flake8-simplify
    "TID",# flake8-tidy-imports
    "ARG",# flake8-unused-arguments
    "RUF",# Ruff-specific rules
]

[tool.ruff.lint.pydocstyle]
convention = "google"

[tool.ty.rules]
all = "warn"

